CREATE SCHEMA reference;

CREATE TABLE reference.commit (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	commit VARCHAR(256) NOT NULL,
	ordinal INTEGER,
	tag VARCHAR(256),
	short_sha TEXT,
	parent_count BIGINT,
	weight DOUBLE PRECISION,
	committed_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT pk_commit PRIMARY KEY (id),
	CONSTRAINT uq_commit_commit UNIQUE (commit),
	CONSTRAINT uq_commit_ordinal UNIQUE (ordinal)
);

CREATE INDEX ix_commit_tag ON reference.commit (tag) WHERE tag IS NOT NULL;

CREATE TABLE reference.machine (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(256) NOT NULL,
	tracked BOOLEAN DEFAULT true NOT NULL,
	hardware TEXT,
	core_count BIGINT,
	clock_ghz DOUBLE PRECISION,
	provisioned_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT pk_machine PRIMARY KEY (id),
	CONSTRAINT uq_machine_name UNIQUE (name)
);

CREATE TABLE reference.metric (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(63) NOT NULL,
	CONSTRAINT pk_metric PRIMARY KEY (id),
	CONSTRAINT uq_metric_name UNIQUE (name)
);

CREATE TABLE reference.test (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(256) NOT NULL,
	CONSTRAINT pk_test PRIMARY KEY (id),
	CONSTRAINT uq_test_name UNIQUE (name)
);

CREATE TABLE reference.regression (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	uuid VARCHAR(36) NOT NULL,
	title VARCHAR(256),
	bug VARCHAR(256),
	notes TEXT,
	state INTEGER NOT NULL,
	commit_id INTEGER,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_regression PRIMARY KEY (id),
	CONSTRAINT ck_regression_state CHECK (state IN (0, 1, 2, 3, 4)),
	CONSTRAINT uq_regression_uuid UNIQUE (uuid),
	CONSTRAINT fk_regression_commit_id_commit FOREIGN KEY(commit_id) REFERENCES reference.commit (id)
);

CREATE INDEX ix_regression_commit_id ON reference.regression (commit_id);

CREATE INDEX ix_regression_created_at_id ON reference.regression (created_at, id);

CREATE INDEX ix_regression_state ON reference.regression (state);

CREATE TABLE reference.run (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	uuid VARCHAR(36) COLLATE "C" NOT NULL,
	machine_id INTEGER NOT NULL,
	commit_id INTEGER NOT NULL,
	submitted_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	run_parameters JSONB DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT pk_run PRIMARY KEY (id),
	CONSTRAINT uq_run_uuid UNIQUE (uuid),
	CONSTRAINT fk_run_machine_id_machine FOREIGN KEY(machine_id) REFERENCES reference.machine (id) ON DELETE CASCADE,
	CONSTRAINT fk_run_commit_id_commit FOREIGN KEY(commit_id) REFERENCES reference.commit (id) ON DELETE CASCADE
);

CREATE INDEX ix_run_commit_id ON reference.run (commit_id);

CREATE INDEX ix_run_machine_id_submitted_at ON reference.run (machine_id, submitted_at);

CREATE INDEX ix_run_submitted_at_id ON reference.run (submitted_at, id);

CREATE TABLE reference.test_coverage (
	machine_id INTEGER NOT NULL,
	test_id INTEGER NOT NULL,
	execution_time BOOLEAN DEFAULT false NOT NULL,
	code_size BOOLEAN DEFAULT false NOT NULL,
	hash BOOLEAN DEFAULT false NOT NULL,
	finished_at BOOLEAN DEFAULT false NOT NULL,
	CONSTRAINT pk_test_coverage PRIMARY KEY (machine_id, test_id),
	CONSTRAINT fk_test_coverage_machine_id_machine FOREIGN KEY(machine_id) REFERENCES reference.machine (id) ON DELETE CASCADE,
	CONSTRAINT fk_test_coverage_test_id_test FOREIGN KEY(test_id) REFERENCES reference.test (id)
);

CREATE TABLE reference.profile (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	uuid VARCHAR(36) NOT NULL,
	run_id INTEGER NOT NULL,
	test_id INTEGER NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	disassembly_format TEXT NOT NULL,
	counters JSONB NOT NULL,
	CONSTRAINT pk_profile PRIMARY KEY (id),
	CONSTRAINT uq_profile_run_id_test_id UNIQUE (run_id, test_id),
	CONSTRAINT uq_profile_uuid UNIQUE (uuid),
	CONSTRAINT fk_profile_run_id_run FOREIGN KEY(run_id) REFERENCES reference.run (id) ON DELETE CASCADE,
	CONSTRAINT fk_profile_test_id_test FOREIGN KEY(test_id) REFERENCES reference.test (id)
);

CREATE INDEX ix_profile_test_id ON reference.profile (test_id);

CREATE TABLE reference.regression_indicator (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	uuid VARCHAR(36) NOT NULL,
	regression_id INTEGER NOT NULL,
	machine_id INTEGER NOT NULL,
	test_id INTEGER NOT NULL,
	metric_id INTEGER NOT NULL,
	CONSTRAINT pk_regression_indicator PRIMARY KEY (id),
	CONSTRAINT uq_regression_indicator_combination UNIQUE (regression_id, machine_id, test_id, metric_id),
	CONSTRAINT uq_regression_indicator_uuid UNIQUE (uuid),
	CONSTRAINT fk_regression_indicator_regression_id_regression FOREIGN KEY(regression_id) REFERENCES reference.regression (id) ON DELETE CASCADE,
	CONSTRAINT fk_regression_indicator_machine_id_machine FOREIGN KEY(machine_id) REFERENCES reference.machine (id) ON DELETE CASCADE,
	CONSTRAINT fk_regression_indicator_test_id_test FOREIGN KEY(test_id) REFERENCES reference.test (id),
	CONSTRAINT fk_regression_indicator_metric_id_metric FOREIGN KEY(metric_id) REFERENCES reference.metric (id) ON DELETE CASCADE
);

CREATE INDEX ix_regression_indicator_machine_id_test_id_metric_id_id ON reference.regression_indicator (machine_id, test_id, metric_id, id);

CREATE TABLE reference.run_summary (
	run_id INTEGER NOT NULL,
	metric_id INTEGER NOT NULL,
	sample_agg VARCHAR(8) NOT NULL,
	geomean DOUBLE PRECISION NOT NULL,
	CONSTRAINT pk_run_summary PRIMARY KEY (run_id, metric_id, sample_agg),
	CONSTRAINT ck_run_summary_sample_agg CHECK (sample_agg IN ('median', 'mean', 'min', 'max')),
	CONSTRAINT fk_run_summary_run_id_run FOREIGN KEY(run_id) REFERENCES reference.run (id) ON DELETE CASCADE,
	CONSTRAINT fk_run_summary_metric_id_metric FOREIGN KEY(metric_id) REFERENCES reference.metric (id) ON DELETE CASCADE
);

CREATE TABLE reference.sample (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	run_id INTEGER NOT NULL,
	test_id INTEGER NOT NULL,
	execution_time DOUBLE PRECISION,
	code_size BIGINT,
	hash TEXT,
	finished_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT pk_sample PRIMARY KEY (id),
	CONSTRAINT fk_sample_run_id_run FOREIGN KEY(run_id) REFERENCES reference.run (id) ON DELETE CASCADE,
	CONSTRAINT fk_sample_test_id_test FOREIGN KEY(test_id) REFERENCES reference.test (id)
);

CREATE INDEX ix_sample_run_id_test_id ON reference.sample (run_id, test_id);

CREATE INDEX ix_sample_test_id_run_id ON reference.sample (test_id, run_id);

CREATE TABLE reference.profile_function (
	profile_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	counters JSONB NOT NULL,
	length INTEGER NOT NULL,
	instructions BYTEA NOT NULL,
	CONSTRAINT pk_profile_function PRIMARY KEY (profile_id, name),
	CONSTRAINT fk_profile_function_profile_id_profile FOREIGN KEY(profile_id) REFERENCES reference.profile (id) ON DELETE CASCADE
)
