#!/bin/bash

# If we passed a cache, just drop it and look like cmake.
if [[ $1 == "-C" ]]; then
    echo "Cmake Cache $2"
    shift
    shift    
fi    
if [[ ! -f $1/CMakeLists.txt ]]; then
  exit 1
else
  cp $1/fake-test $1/fake-results.json .
  echo "Dummy" > CMakeCache.txt
  mkdir subtest
  cp $1/fake-test $1/fake-results.json subtest
  exit 0
fi
