name: Check installation

permissions:
  contents: read

on:
  - push
  - pull_request

jobs:
  check-installation:
    runs-on: ubuntu-latest
    name: "Python ${{ matrix.python-version }}"

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false

    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PostgreSQL development headers
      run: sudo apt-get install -y libpq-dev
    - name: Check client installation
      run: |
        python -m venv .venv-client
        .venv-client/bin/python -m pip install -r requirements.client.txt
        .venv-client/bin/lnt create lnt-client-instance
    - name: Check server installation
      run: |
        python -m venv .venv-server
        .venv-server/bin/python -m pip install -r requirements.server.txt
        .venv-server/bin/lnt create lnt-server-instance
